// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvN4PkROrFnfUPUEQ76orTKSQeX2N3_Ec',
    appId: '1:613425170941:web:e489bf3bdbc94ded0a3194',
    messagingSenderId: '613425170941',
    projectId: 'applooks-98fec',
    authDomain: 'applooks-98fec.firebaseapp.com',
    storageBucket: 'applooks-98fec.appspot.com',
    measurementId: 'G-14KC4D3S3G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSb99bqBmr9yudhShAO1C99jxh9iJzPEk',
    appId: '1:613425170941:android:2db89221739e04c30a3194',
    messagingSenderId: '613425170941',
    projectId: 'applooks-98fec',
    storageBucket: 'applooks-98fec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTI6kwNPVWrfgfBk1SwiHs_jg8Dl2C-ZI',
    appId: '1:613425170941:ios:17bf2303bbfdb1cb0a3194',
    messagingSenderId: '613425170941',
    projectId: 'applooks-98fec',
    storageBucket: 'applooks-98fec.appspot.com',
    iosBundleId: 'com.example.appLook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTI6kwNPVWrfgfBk1SwiHs_jg8Dl2C-ZI',
    appId: '1:613425170941:ios:17bf2303bbfdb1cb0a3194',
    messagingSenderId: '613425170941',
    projectId: 'applooks-98fec',
    storageBucket: 'applooks-98fec.appspot.com',
    iosBundleId: 'com.example.appLook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvN4PkROrFnfUPUEQ76orTKSQeX2N3_Ec',
    appId: '1:613425170941:web:70f71c3a2b70d7f70a3194',
    messagingSenderId: '613425170941',
    projectId: 'applooks-98fec',
    authDomain: 'applooks-98fec.firebaseapp.com',
    storageBucket: 'applooks-98fec.appspot.com',
    measurementId: 'G-F9W3HQR7M1',
  );
}
